mode: ContinuousDeployment
branches:
  main:
    tag: ''
    increment: Minor
    prevent-increment-of-merged-branch-version: true
    track-merge-target: true
    regex: ^main$
    source-branches:
      - develop
  develop:
    tag: 'beta'
    increment: Patch
    track-merge-target: true
    regex: ^develop$
  feature:
    tag: 'alpha'
    increment: Patch
    regex: ^features?[\\/]
  hotfix:
    tag: 'hotfix'
    increment: Patch
    regex: ^hotfix[\\/]
  release:
    tag: 'rc'
    increment: Minor
    regex: ^release[\\/]
  support:
    tag: 'support'
    increment: Patch
    regex: ^support[\\/]
versioning-strategy: ContinuousDeployment
assembly-versioning-scheme: MajorMinorPatch
commit-date-format: yyyy-MM-dd
ignore:
  sha: []
