mode: ContinuousDeployment
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'
assembly-versioning-scheme: MajorMinorPatch
tag-prefix: 'v'
commit-message-incrementing: Enabled
commit-date-format: yyyy-MM-dd
versioning-strategy: ContinuousDeployment

branches:
  main:
    regex: ^main$
    tag: ''
    increment: Minor
    prevent-increment-of-merged-branch-version: true
    track-merge-target: true
    source-branches:
      - develop
  
  develop:
    regex: ^develop$
    tag: 'beta'
    increment: Patch
    track-merge-target: true
  
  feature:
    regex: ^features?[\\/]
    tag: 'alpha'
    increment: Patch
  
  hotfix:
    regex: ^hotfix[\\/]
    tag: 'hotfix'
    increment: Patch
  
  release:
    regex: ^release[\\/]
    tag: 'rc'
    increment: Minor
  
  support:
    regex: ^support[\\/]
    tag: 'support'
    increment: Patch
  
  pull-request:
    tag: 'pr'
    increment: Inherit
    tag-number-pattern: '[/-](?<number>\d+)[-/]'

ignore:
  sha: []